version: ~> 1.0


import:
  - hapijs/ci-config-travis:node_js.yml@main
  - hapijs/ci-config-travis:install_plugin.yml@main
  - hapijs/ci-config-travis:env.yml@main

services:
  - docker

before_script:
  - docker-compose up -d
  - sleep 5
